version: '3'

services:
  app:
    build: .
    depends_on:
      - prometheus
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./requirements.txt:/app/requirements.txt
      - ./utils:/app/utils
      - ./models:/app/models
      - ./data:/app/data
      - ./tests:/app/tests
    environment:
      - MODULE_NAME=api.main
      - VARIABLE_NAME=app
      - API_KEY=dead-beef-15-bad-f00d
      - DEBUG=true

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=zorzi
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
volumes:
  grafana-storage: