name: Executar Testes com Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Subir serviços com Docker Compose
        run: |
          docker-compose up -d

      - name: Executar testes
        run: |
          docker-compose exec app pytest --cov=.

      - name: Parar serviços
        run: |
          docker-compose down